debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pguser
    password: pgpassword
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
  web:
    resources:
      static-locations: file:src/main/resources/static
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR